version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=chatwoot_prod
      - POSTGRES_PASSWORD=chatwoot_prod
      - POSTGRES_DATABASE=chatwoot_production
      - SIDEKIQ_CONCURRENCY=10
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=chatwoot_prod
      - POSTGRES_PASSWORD=chatwoot_prod
      - POSTGRES_DB=chatwoot_production
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=chatwoot_prod
      - POSTGRES_PASSWORD=chatwoot_prod
      - POSTGRES_DATABASE=chatwoot_production
      - SIDEKIQ_CONCURRENCY=10
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:
